const String DATABASE_NAME = 'receitas';

const String RECEITAS_TABLE_NAME = 'receitas';
const String RECEITAS_COLUMN_RECEITAID = 'receitaID';
const String RECEITAS_COLUMN_TITLE = 'title';
const String RECEITAS_COLUMN_DESCRIPTION = 'description';
const String RECEITAS_COLUMN_CATEGORY = 'category';

const String CREATE_RECEITAS_TABLE_SCRIPT = '''
CREATE TABLE $RECEITAS_TABLE_NAME
(
  $RECEITAS_COLUMN_RECEITAID INTEGER PRIMARY KEY,
  $RECEITAS_COLUMN_TITLE TEXT.
  $RECEITAS_COLUMN_DESCRIPTION TEXT,
  $RECEITAS_COLUMN_CATEGORY TEXT
)
''';
