// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtnX_TmBmvLRMveGSCxidCURn5C3k8ShQ',
    appId: '1:735299593976:web:450212ced213c83840fd0d',
    messagingSenderId: '735299593976',
    projectId: 'receitas-10b21',
    authDomain: 'receitas-10b21.firebaseapp.com',
    storageBucket: 'receitas-10b21.appspot.com',
    measurementId: 'G-YH31LYCW4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsRkaB38_wHH_VRNURfElg_niCyW2Ekas',
    appId: '1:735299593976:android:7295c5b2754b046640fd0d',
    messagingSenderId: '735299593976',
    projectId: 'receitas-10b21',
    storageBucket: 'receitas-10b21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB90uvoSIae3a7fi69yurfTzpBtDtDWhrk',
    appId: '1:735299593976:ios:e3a05e9bbb86540140fd0d',
    messagingSenderId: '735299593976',
    projectId: 'receitas-10b21',
    storageBucket: 'receitas-10b21.appspot.com',
    iosClientId: '735299593976-jntm71a7pploh05ktt2m0rceree850i9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB90uvoSIae3a7fi69yurfTzpBtDtDWhrk',
    appId: '1:735299593976:ios:e3a05e9bbb86540140fd0d',
    messagingSenderId: '735299593976',
    projectId: 'receitas-10b21',
    storageBucket: 'receitas-10b21.appspot.com',
    iosClientId: '735299593976-jntm71a7pploh05ktt2m0rceree850i9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
